spring.application.name=AppointmentMS
server.port=8082

# Database URL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hms_appointmentdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Secrate Key
SECRET_KEY=SSWuHijaMXSWyVtU2NERpKPGXF0hPN2

#Exception Keywords
APPOINTMENT-NOT-FOUND = Appointment not found
APPOINTMENT-ALREADY-CANCELLED = Appointment already cancelled
DOCTOR_NOT_FOUND=Doctor Not Found 
PATIENT_NOT_FOUND=Patient Not Found
DOCTOR_OR_PATIENT_DETAILS_NOT_FOUND=Doctor or Patient details not found

#Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

app.cors.allowed-origin=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
profiles.url=${PROFILEMS_URL:http://localhost:8081}

logging.file.name=../logs/${spring.application.name}.log
logging.level.com.hms.user=DEBUG
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
