spring.application.name=ProfileMs


server.port=8081

# Database URL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hms_profiledb?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


SECRET_KEY=SSWuHijaMXSWyVtU2NERpKPGXF0hPN2

DOCTOR_EMAIL_ALREADY_EXISTS=Doctor Email Already Exists
DOCTOR_LICENCE_NO_ALREADY_EXISTS=Doctor LicenceNo Already Exixts
DOCTOR_NOT_FOUND=Doctor Not Found 
PATIENT_EMAIL_ALREADY_EXISTS=Patient Email Already Exists
PATIENT_AADHAR_ALREADY_EXISTS=Patient AadharNo Already Exixts
PATIENT_NOT_FOUND=Patient Not Found 

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

profiles.url=${PROFILEMS_URL:http://localhost:8081}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

logging.file.name=../logs/${spring.application.name}.log
logging.level.com.hms.user=DEBUG
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
