# =================================
# Application
# =================================
spring.application.name=GatewayMS

# =================================
# Server
# =================================
server.port=9000


# =================================
# Gateway Default Filters
# =================================
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE


# =================================
# CORS
# =================================
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*

spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true


# =================================
# UserMS
# =================================
spring.cloud.gateway.routes[0].id=UserMS

spring.cloud.gateway.routes[0].uri=${USERMS_URL:lb://UserMS}

spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[0].filters[0]=TokenFilter


# =================================
# ProfileMS
# =================================
spring.cloud.gateway.routes[1].id=ProfileMs

spring.cloud.gateway.routes[1].uri=${PROFILEMS_URL:lb://ProfileMs}

spring.cloud.gateway.routes[1].predicates[0]=Path=/profile/**

spring.cloud.gateway.routes[1].filters[0]=TokenFilter


# =================================
# Eureka
# =================================
eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}