spring.application.name=Eureka-Server
server.port=8761

# Eureka Server should not register itself
eureka.client.register-with-eureka=false

# Eureka Server should not fetch another registry
eureka.client.fetch-registry=false

# Eureka Server settings
eureka.server.enable-self-preservation=true